### ISSUE TITLE
Wikidata5M失效问题

### ISSUE THREAD

**Issue by Eutopun** [intfloat/SimKGC#15]
您好，对您的工作非常感兴趣，感觉您的实验效果很好，所以想复现一下。但是，我在下载Wikidata5M数据集的时候，链接好像都失效了，请问，能上传一下Wikidata5M的数据集吗？非常感谢！
祝您身体健康，每天开心！！！！

**Comment by Eutopun** [comment]
非常期待您的回复！！再次表达感谢！！

**Comment by intfloat** [comment]
Hi,

The dataset authors seem to have removed the hosted data. I have uploaded a copy to Huggingface and updated the dataset download script.

Please check out and run [https://github.com/intfloat/SimKGC/blob/main/scripts/download_wikidata5m.sh](https://github.com/intfloat/SimKGC/blob/main/scripts/download_wikidata5m.sh) to download the Wikidata5M.

Thanks,
Liang

**Comment by Eutopun** [comment]
太及时了，非常感谢！！望身体健康。

**Comment by cyjie429** [comment]
太及时了，非常感谢！！望身体健康！！
