### ISSUE TITLE
Pretrained Language Models (like BERT) with embedding-based models (like TransE)

### ISSUE THREAD

**Issue by sm354** [intfloat/SimKGC#2]
Hi Liang,

Have you tried any experiments on using embedding-based models (like TransE) along with Pretrained LM as encoder? For instance, using BERT for encoding the subject, relation, and object (all separately), and passing these embeddings (e_head, e_relation, e_tail) to TransE and optimizing the transE objective function. BERT parameters are allowed to be fine-tuned.

**Comment by intfloat** [comment]
That's a straightforward way to combine BERT and embedding-based models. As far as I know, at least two papers ([BLP](https://arxiv.org/pdf/2010.03496.pdf) and [KEPLER](https://arxiv.org/pdf/1911.06136.pdf)) use this method for training.

We directly compare with results from these papers and did not run such experiments by ourselves. Concatenating subject and relation texts allows richer interactions between them, which should translate into better results, unless it is critical to have separate entity and relation embeddings.

**Comment by sm354** [comment]
Thank you very much for clarification and sharing the related papers!

**Comment by yw3l** [comment]
Hi, @sm354 
Have you tried combining BERT with embedded models, such as TransE?

**Comment by sm354** [comment]
Hi @yw3l, I think I did not try as it was already done in the papers shared by @intfloat but I also remember that I was facing OOM issue if the subject, relation and object are separately encoded using BERT (unlike in SimKGC which clubs subject and relation together). It had been a long time when I was doing it so I might be wrong as well.

**Comment by yw3l** [comment]
hi, @sm354 Thank you very much for sharing related information.
