### ISSUE TITLE
为什么在训练过程中标签是生成的，而不是使用真实的标签

### ISSUE THREAD

**Issue by YongqingQI** [intfloat/SimKGC#26]
labels = torch.arange(batch_size).to(hr_vector.device)

在训练过程中，为啥用arange生成标签，而不是使用真实的标签呢？

**Comment by intfloat** [comment]
这就是真实的标签，对比学习中第`i`个query和第`i`个key是互为正例的关系，可以参考 [SimCLR](https://arxiv.org/pdf/2002.05709) 这篇论文。
