### ISSUE TITLE
您好，我有个问题关于best_mode和last_model?

### ISSUE THREAD

**Issue by YongqingQI** [intfloat/SimKGC#35]
训练过程中，acc@1结果最好的模型被保存为best_model，为什么测试阶段却用的是last_model呢，而且在测试阶段best_model的效果比last_model差很多

**Comment by intfloat** [comment]
因为 best_model 计算的指标只是一个batch内部排序的结果，并不能反应最终整体排序的结果，所以为了简单起见，就直接评测 last_model 了。

但是 best_model 和 last_model 也不应该差很多，我记得效果是很接近的。

**Comment by YongqingQI** [comment]
噢噢，感谢！
