### ISSUE TITLE
关于wikidata5m的text 的问题

### ISSUE THREAD

**Issue by EurusNotes** [intfloat/SimKGC#9]
您好，intfloat. 打扰了。

我最近正在阅读您的代码。
关于wikidata5M的 Entity 的文本描述数据的读取，我有一个疑问。

```
def _truncate(text: str, max_len: int):
    return ' '.join(text.split()[:max_len])


def _load_wiki5m_id2text(path: str, max_len: int = 30):
    global wiki5m_id2text
    for line in open(path, 'r', encoding='utf-8'):
        fs = line.strip().split('\t')
        assert len(fs) >= 2, 'Invalid line: {}'.format(line.strip())
        ent_id, ent_text = fs[0], ' '.join(fs[1:])
        wiki5m_id2text[ent_id] = _truncate(ent_text, max_len)

    print('Load {} entity texts from {}'.format(len(wiki5m_id2text), path))
```

我统计了一下text的长度确实非常长，全部放到BERT里面是比较困难的，所以需要限制text的长度。
但是为什么 max_len 设定为30呢？
是您通过了分析之后发现了 Head Entity 一定出现在长度30以内的文本当中吗？

如果可以回答我的问题会非常帮助到我，期待您的回复。

**Comment by intfloat** [comment]
你好，

在送给bert的输入中，是head entity的名称和描述文本拼在一起的，参考 https://github.com/intfloat/SimKGC/blob/2139ac1573970bd93a4ce261f815da6b31f62b6a/doc.py#L95 所以即使把描述文本截断到30个token，模型总是能够看得到head entity的名称。

至于为什么max_len = 30，主要原因是对比学习训练需要大的batch size效果才会好，长度太大的话gpu memory撑不住。

谢谢。

**Comment by EurusNotes** [comment]
您好，非常感谢您的快速回复！！！感谢！！:)
